apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-hello-world-hpa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-hello-world
  template:
    metadata:
      labels:
        app: mern-hello-world
    spec:
      containers:
        - name: mern-hello-world
          image: jyotiprakashh/hello-world:hpa
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
